name: Main workflow
on: push
env: # Set the secret as an input
  docker_username: stelllarce
  docker_password: ${{ secrets.GITHUB_TOKEN }} #Nees to be set to be made available to the workflow
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Snyk:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Run snyk
        working-directory: ${{github.workspace}}/src
        run: |
          pip install -r requirements.txt
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test